spring:
    database:
        driverClassName: com.mysql.jdbc.Driver
    datasource:
        platform: mysql
        username: root
        password: root
    jpa:
        database: MYSQL
        show-sql: true
        generate-ddl: true
        hibernate:
          ddl-auto: create

# Eureka Settings
# ---------------
eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
    client:
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
#            defaultZone: ${DISCOVERY_SERVICE_URI:http://localhost:${DISCOVERY_SERVICE_PORT:8761}}/eureka/

